/*Кастом*/
concommand.Add("/custom", function()
net.Start("rp.ApplyGenome")
net.WriteUInt(0, 5)
net.WriteUInt(15, 5)
net.WriteUInt(15, 5)
net.SendToServer()
net.Start("rp.ApplyGenome")
net.WriteUInt(20, 5)
net.WriteUInt(5, 5)
net.WriteUInt(5, 5)
net.SendToServer()
net.Start("rp.ApplyGenome")
net.WriteUInt(0, 5)
net.WriteUInt(0, 5)
net.WriteUInt(0, 5)
net.SendToServer()
net.Start("rp.ApplyGenome")
net.WriteUInt(5, 5)
net.WriteUInt(5, 5)
net.WriteUInt(20, 5)
net.SendToServer()
net.Start("rp.ApplyGenome")
net.WriteUInt(5, 5)
net.WriteUInt(20, 5)
net.WriteUInt(5, 5)
net.SendToServer()
end)

/*Элита*/
concommand.Add("/elite", function()
net.Start("rp.ApplyGenome")
net.WriteUInt(5, 5)
net.WriteUInt(5, 5)
net.WriteUInt(20, 5)
net.SendToServer()
end)

/*Джаггернаут*/
concommand.Add("/jugger", function()
net.Start("rp.ApplyGenome")
net.WriteUInt(20, 5)
net.WriteUInt(5, 5)
net.WriteUInt(5, 5)
net.SendToServer()
end)

/*Скаут*/
concommand.Add("/scout", function()
net.Start("rp.ApplyGenome")
net.WriteUInt(5, 5)
net.WriteUInt(20, 5)
net.WriteUInt(5, 5)
net.SendToServer()
end)

/*Снайпер*/
concommand.Add("/sniper", function()
net.Start("rp.ApplyGenome")
net.WriteUInt(0, 5)
net.WriteUInt(0, 5)
net.WriteUInt(0, 5)
net.SendToServer()
end)

/*Полицейский*/
concommand.Add("/police", function()
net.Start("rp.ApplyGenome")
net.WriteUInt(10, 5)
net.WriteUInt(10, 5)
net.WriteUInt(10, 5)
net.SendToServer()
end)

/*Нападение*/
concommand.Add("/napadenie", function()
net.Start("rp.ApplyGenome")
net.WriteUInt(0, 5)
net.WriteUInt(15, 5)
net.WriteUInt(15, 5)
net.SendToServer()
end)

--шпиона нет потому что он юзлесс
print("Voenkom loh")
